name: Build, Push, Deploy.

on:
  push:
    branches: [ main ]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install dependencies
        run: python -m pip install --upgrade pip setuptools wheel pre-commit
      - name: Linting
        run: make linting